name: Call Dependabot reviewer

on:
  pull_request:
    types: [opened, synchronize, reopened]

jobs:
  shared-workflows:
    uses: Sundsvallskommun/shared-workflows/.github/workflows/common-dependabot-reviewer.yml@main
    secrets: inherit
