name: "Call Dependabot reviewer"

on:
pull_request_target:

jobs:
  shared-workflows:
    uses: Sundsvallskommun/shared-workflows/.github/workflows/common-dependabot-reviewer.yml@main
    permissions:
      pull-requests: write
      contents: write
    secrets:
      UTVECKLINGSFABRIKEN_DEPENDABOT_AUTOREVIEW_TOKEN: ${{ secrets.UTVECKLINGSFABRIKEN_DEPENDABOT_AUTOREVIEW_TOKEN}}
